title: "William Haw"
author: "William Haw"
description: "Software Engineer"

# Jekyll settings
permalink: /:title/          # see https://jekyllrb.com/docs/permalinks/
paginate: 5                  # number of articles per page, remove to disable pagination
excerpt_separator: <!--excerpt-->  # indicates the end of the excerpt

# Page settings
show_excerpts: true          # show article previews on the home page instead of headlines
hide_title: true            # remove site heading in the header
post_footer: true            # show previous and next links at the end of each post
date_format: "%A, %e %B %Y"     # see http://shopify.github.io/liquid/filters/date/
mathjax: true

# Theme settings
style: default               # choose between "default", "contrast" and "minimal"
dark_theme: false            # enables dark mode

navigation:                  # (optional) site navigation in the header
  - index.html
  - archive.md
  - about.md

icons:                       # (optional) icons in the header, see http://fontawesome.com/icons
  github: "https://github.com/williamhaw"
  linkedin: "https://www.linkedin.com/in/william-haw-b3902115b"
  rss: "/feed.xml"

comments:                    # embed disqus or isso comments
  disqus: "williamhaw"

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-135432016-1

plugins: 
 - jekyll-feed
 - jekyll-paginate
 - jekyll-default-layout
 - jekyll-sitemap

exclude:
 - Gemfile
 - Gemfile.lock
 - LICENSE
 - README.md
 - CNAME