version: "3.8"

services:
  blog:
    build: .
    image: jekyll/jekyll:4
    volumes:
      - .:/opt
    working_dir: /opt
    command: sh -c "bundle install && bundle exec jekyll serve --host 0.0.0.0"
    ports:
      - 4000:4000